version: "3.8"
services:
  app:
    build: .
    container_name: pkchart-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/collectiondb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRINGDOC_SWAGGER_UI_DISABLE_SWAGGER_DEFAULT_URL=true
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger
      - JWT_SECRET=${JWT_SECRET}
      - LOGGING_LEVEL_ORG_MAGNUSCHASE_PKCHART_SECURITY=DEBUG
    networks:
      - pkchart-network

  db:
    image: postgres:15
    container_name: pkchart-db
    environment:
      POSTGRES_DB: collectiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - pkchart-network

volumes:
  pgdata:

networks:
  pkchart-network:
    driver: bridge
